name: Release

on:
  push:
    tags:
      - "v*"

# Prevent multiple workflows from running at the same time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Delete existing release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          gh release delete "${{ github.ref_name }}" --yes || true
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - run: npm ci

      - uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NODE_OPTIONS: "--max-old-space-size=4096"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: dist/
