name: Release

on:
  push:
    tags:
      - 'v*'

# Prevent multiple workflows from running at the same time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean up existing release assets
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RELEASE_ID=$(gh api repos/${{ github.repository }}/releases/tags/$TAG_NAME --jq .id)
          if [ ! -z "$RELEASE_ID" ]; then
            gh api repos/${{ github.repository }}/releases/$RELEASE_ID/assets --jq '.[].id' | xargs -I {} gh api repos/${{ github.repository }}/releases/assets/{} -X DELETE
          fi
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: dist/ 